# Generated by Django 3.1.7 on 2021-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20210301_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='details',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique_for_date='published'),
        ),
    ]
